### ISSUE TITLE
"Enable SDOH Classification" is not turning off on /services page

### ISSUE THREAD

**Issue by royappa** [royappa/orservices#1]
Under Admin -> Settings -> Appearance I set "Enable SDOH Classification" to No and hit Submit.
I got a "success" green confirmation.
However on the /services URL, the two dropdowns are still showing.

Desired behavior: if this value is false, then those two dropdowns should not show on /services.

**Comment by CleberTrichez** [comment]
done & site updated.

**Comment by royappa** [comment]
Reviewed, see comment in commit.
